[package]
name = "brainfuck-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
anyhow = "1.0.93"
pest_derive = "2.7.14"
pest = "2.7.14"
